"""add_immich_support

Revision ID: 0ad99dfbe7ec
Revises: 9b1c2d3e4f5g
Create Date: 2026-01-15 22:03:19.362652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ad99dfbe7ec'
down_revision = '9b1c2d3e4f5g'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_sqlite = conn.dialect.name == "sqlite"

    op.create_table('integration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('external_user_id', sa.String(length=255), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('import_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_index('idx_integration_active_provider', 'integration', ['is_active', 'provider'], unique=False)
    op.create_index('idx_integration_last_synced', 'integration', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_integration_id'), 'integration', ['id'], unique=False)
    op.create_index(op.f('ix_integration_provider'), 'integration', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_user_id'), 'integration', ['user_id'], unique=False)
    if is_sqlite:
        with op.batch_alter_table('entry') as batch_op:
            batch_op.alter_column('weather_summary',
                       existing_type=sa.TEXT(),
                       type_=sqlmodel.sql.sqltypes.AutoString(),
                       existing_nullable=True)
    else:
        op.alter_column('entry', 'weather_summary',
                   existing_type=sa.TEXT(),
                   type_=sqlmodel.sql.sqltypes.AutoString(),
                   existing_nullable=True)
    op.add_column('entry_media', sa.Column('external_provider', sa.String(length=50), nullable=True))
    op.add_column('entry_media', sa.Column('external_asset_id', sa.String(length=255), nullable=True))
    op.add_column('entry_media', sa.Column('external_url', sa.String(length=512), nullable=True))
    op.add_column('entry_media', sa.Column('external_created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entry_media', sa.Column('external_metadata', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    if is_sqlite:
        with op.batch_alter_table('entry_media') as batch_op:
            batch_op.alter_column('file_path',
                       existing_type=sa.VARCHAR(length=500),
                       nullable=True)
            batch_op.alter_column('file_size',
                       existing_type=sa.INTEGER(),
                       nullable=True)
    else:
        op.alter_column('entry_media', 'file_path',
                   existing_type=sa.VARCHAR(length=500),
                   nullable=True)
        op.alter_column('entry_media', 'file_size',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    op.create_index('idx_entry_media_external_provider', 'entry_media', ['external_provider', 'external_asset_id'], unique=False)
    op.create_index(op.f('ix_entry_media_external_asset_id'), 'entry_media', ['external_asset_id'], unique=False)
    op.create_index(op.f('ix_entry_media_external_provider'), 'entry_media', ['external_provider'], unique=False)
    op.add_column('import_jobs', sa.Column('entry_id', sa.Uuid(), nullable=True))
    op.add_column(
        'import_jobs',
        sa.Column('failed_items', sa.Integer(), nullable=False, server_default=sa.text("0"))
    )
    if is_sqlite:
        with op.batch_alter_table('import_jobs') as batch_op:
            batch_op.alter_column('failed_items', server_default=None)
    else:
        op.alter_column('import_jobs', 'failed_items', server_default=None)
    op.add_column('import_jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    if is_sqlite:
        with op.batch_alter_table('import_jobs') as batch_op:
            batch_op.alter_column('file_path',
                       existing_type=sa.VARCHAR(),
                       nullable=True)
    else:
        op.alter_column('import_jobs', 'file_path',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
    op.create_index(op.f('ix_import_jobs_entry_id'), 'import_jobs', ['entry_id'], unique=False)
    fk_name = "fk_import_jobs_entry_id_entry"
    if is_sqlite:
        with op.batch_alter_table('import_jobs') as batch_op:
            batch_op.create_foreign_key(fk_name, 'entry', ['entry_id'], ['id'], ondelete='CASCADE')
    else:
        op.create_foreign_key(fk_name, 'import_jobs', 'entry', ['entry_id'], ['id'], ondelete='CASCADE')
    if conn.dialect.name == "postgresql":
        op.execute("ALTER TYPE import_source_type_enum ADD VALUE IF NOT EXISTS 'immich'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    is_sqlite = conn.dialect.name == "sqlite"

    op.create_unique_constraint(op.f('uq_instance_details_singleton'), 'instance_details', ['singleton_marker'], postgresql_nulls_not_distinct=False)
    fk_name = "fk_import_jobs_entry_id_entry"
    if is_sqlite:
        with op.batch_alter_table('import_jobs') as batch_op:
            batch_op.drop_constraint(fk_name, type_='foreignkey')
    else:
        op.drop_constraint(fk_name, 'import_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_import_jobs_entry_id'), table_name='import_jobs')
    if is_sqlite:
        with op.batch_alter_table('import_jobs') as batch_op:
            batch_op.alter_column('file_path',
                       existing_type=sa.VARCHAR(),
                       nullable=False)
    else:
        op.alter_column('import_jobs', 'file_path',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    op.drop_column('import_jobs', 'started_at')
    op.drop_column('import_jobs', 'failed_items')
    op.drop_column('import_jobs', 'entry_id')
    op.drop_index(op.f('ix_entry_media_external_provider'), table_name='entry_media')
    op.drop_index(op.f('ix_entry_media_external_asset_id'), table_name='entry_media')
    op.drop_index('idx_entry_media_external_provider', table_name='entry_media')
    if is_sqlite:
        with op.batch_alter_table('entry_media') as batch_op:
            batch_op.alter_column('file_size',
                       existing_type=sa.INTEGER(),
                       nullable=False)
            batch_op.alter_column('file_path',
                       existing_type=sa.VARCHAR(length=500),
                       nullable=False)
    else:
        op.alter_column('entry_media', 'file_size',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        op.alter_column('entry_media', 'file_path',
                   existing_type=sa.VARCHAR(length=500),
                   nullable=False)
    op.drop_column('entry_media', 'external_metadata')
    op.drop_column('entry_media', 'external_created_at')
    op.drop_column('entry_media', 'external_url')
    op.drop_column('entry_media', 'external_asset_id')
    op.drop_column('entry_media', 'external_provider')
    if is_sqlite:
        with op.batch_alter_table('entry') as batch_op:
            batch_op.alter_column('weather_summary',
                       existing_type=sqlmodel.sql.sqltypes.AutoString(),
                       type_=sa.TEXT(),
                       existing_nullable=True)
    else:
        op.alter_column('entry', 'weather_summary',
                   existing_type=sqlmodel.sql.sqltypes.AutoString(),
                   type_=sa.TEXT(),
                   existing_nullable=True)
    op.drop_index(op.f('ix_integration_user_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_provider'), table_name='integration')
    op.drop_index(op.f('ix_integration_id'), table_name='integration')
    op.drop_index('idx_integration_last_synced', table_name='integration')
    op.drop_index('idx_integration_active_provider', table_name='integration')
    op.drop_table('integration')
    # ### end Alembic commands ###
