"""add instance_details table with plus secret

Revision ID: f0cf0baa6c0d
Revises: def789abc123
Create Date: 2026-01-03 14:02:11.871424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid


# revision identifiers, used by Alembic.
revision = 'f0cf0baa6c0d'
down_revision = 'def789abc123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Detect database dialect and use appropriate UUID type
    conn = op.get_bind()
    if conn.dialect.name == "sqlite":
        id_type = sa.String(36)
    else:
        id_type = postgresql.UUID(as_uuid=True)

    op.create_table('instance_details',
    sa.Column('id', id_type, nullable=False, default=uuid.uuid4),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('install_id', sa.String(), nullable=False),
    sa.Column('signed_license', sa.String(), nullable=True),
    sa.Column('license_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('plus_instance_secret', sa.String(), nullable=True),
    sa.Column('singleton_marker', sa.Integer(), nullable=False, server_default='1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton_marker', name='uq_instance_details_singleton')
    )
    op.create_index(op.f('ix_instance_details_id'), 'instance_details', ['id'], unique=False)
    op.create_index(op.f('ix_instance_details_install_id'), 'instance_details', ['install_id'], unique=True)
    op.create_index(op.f('ix_entry_entry_datetime_utc'), 'entry', ['entry_datetime_utc'], unique=False)
    op.create_index(op.f('ix_entry_user_id'), 'entry', ['user_id'], unique=False)
    op.create_index(op.f('ix_mood_log_logged_datetime_utc'), 'mood_log', ['logged_datetime_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mood_log_logged_datetime_utc'), table_name='mood_log')
    op.drop_index(op.f('ix_entry_user_id'), table_name='entry')
    op.drop_index(op.f('ix_entry_entry_datetime_utc'), table_name='entry')
    op.drop_constraint('uq_instance_details_singleton', 'instance_details', type_='unique')
    op.drop_index(op.f('ix_instance_details_install_id'), table_name='instance_details')
    op.drop_index(op.f('ix_instance_details_id'), table_name='instance_details')
    op.drop_table('instance_details')
    # ### end Alembic commands ###
